### PR TITLE
Add patches_ignore magic comment

### PR DESCRIPTION
**Pull request by djipko**
Resolves issue #37

### CODE REVIEW

**Comment by apevec** [comment]
:+1: from me
@yac any comments left from your side?

**Comment by apevec** [comment]
@yac ping

**Comment by yac** [comment]
Thanks Nikola, for making `rdopkg` better for everyone.

**Comment by yazug** [comment]
+1 from me. Nice feature!

**Comment by yac** [comment]
This feature is supported in `rdopkg >= 0.33`.

**Pull request merged**
