### PR TITLE
Add the --filter-out option to update-patches

### LINKED ISSUE #37: Instead of only looking at patches-base line in the spec file, allow for filtering out patches by regex
Problem we are trying to solve:
---

Because our CI configuration is part of the branch we use to generate patches with the help of rdopkg update-patches action, our current workflow for modifying it is as follows:

1) Propose a change that affects the CI config in gerrit
2) Wait for CI, see if results are satisfactory and merge the change

Instead of being done, we now have to *also* do the following set of tasks that make us sad:

3) rebase the branch that the patch just merged on so as to move the CI config patch to the "bottom" so that it will not be caught and added to dist-git on the next run of rdopkg update-patches
4) Update the spec file in dist-git by just changing the patches_base comment line (sometimes this is not possible at all for reasons I won't get into here. In this case we are **very** sad).
5) Push the dist-git change
6) Force push the branch we just rebased to gerrit. Since CI config does not get worked on a lot in parallel this does not really break people, but it is very brittle and, honestly, annoying.

What we propose to do:
---

Add a --filter-out (or similar) switch to the update-patches action which would allow for an arbitrary regex to be passed, this regex would filter out any patches that would otherwise end up in the dist-git repo, and have commit messages that match the regex (or at least title lines). So we could do something like:

`$rdopkg update-patches --filter-out "^CI-CONFIG.*" ` which would generate patches from a) commits above patches_base so that we are backwards compatible b) that have commit messages that **do no*t* start with "CI-CONFIG"

If the maintainers of rdopkg are on board with this idea - I'd be happy to hack up a patch to do this.

### PR DESCRIPTION
**Pull request by djipko**
This patch resolves #37

### CODE REVIEW

**Comment by mdbooth** [comment]
Incidentally, I also think it's important for our use case that rdopkg should be able to pull the name of the tag out of the spec file, same as patches_base.

**Comment by djipko** [comment]
Fair points - thanks Matt.

Let me look into how we could make format patch do this without considering the whole commit message as that would be preferable.

Agreed on being able to set this in the spec file - should be an easy enough add.

**Comment by apevec** [comment]
:+1: for # filter_out "magic" comment
:-1 for adding --fliter-out new CLI option

**Comment by djipko** [comment]
Thanks for the Feedback @apevec . Will respin with that in mind.

**Comment by djipko** [comment]
Updated per comments - there is a limitation to the current implementation that is described in the commit message of the last patch.

I could cook up a refactoring that makse it nicer, but IMHO we should not hold up this feature on that.

**Comment by apevec** [comment]
:+1: @yac please review and merge if it works, refactoring can come later

**Comment by apevec** [comment]
TODO 
* man page fix
* patch file renumbering to avoid silently loses

**Comment by djipko** [comment]
Surpassed by pull request #43

**Pull request closed without merging**
