### PR TITLE
Add clone "-g" option that creates needed Gerrit remotes

### PR DESCRIPTION
**Pull request by cschwede**
This requires a distgit and patches entry in ~/.rdopkg/rdoinfo/rdo.yml, for
example:
```
- project: sample
  conf: core
  distgit: ssh://rpmfactory.beta.rdoproject.org:29418/%(project)s-distgit
  patches: ssh://rpmfactory.beta.rdoproject.org:29418/%(project)s
  maintainers:
  - cschwede@redhat.com
```

### CODE REVIEW

**Comment by yac** [comment]
So if I get it right, this creates two redundant remotes:

    origin == gerrit-origin
    patches == gerrit-patches

What exactly are they needed for?

#49 uses `patches` remote.

**Comment by cschwede** [comment]
Yes, if you start from scratch these branches will be identical. The idea behind this is to be able to setup a branch that is used with Gerrit, while still being able to use a branch for example with the repository located on Github. So it's simply to allow different remotes.

**Comment by apevec** [comment]
@yac if any other concerns left, let's discuss it on the phone

**Comment by apevec** [comment]
@yac there will be some redundancy as we're adding extensions needed for the new workflow with softwarefactory while keeping and not breaking the old workflow, so we can run them in parallel

**Comment by yac** [comment]
Fair enough.

**Pull request merged**
