### PR TITLE
Enable patches stored as unmerged Gerrit reviews

### PR DESCRIPTION
**Pull request by cschwede**
Adds a -g option to "rdopkg patch" command to instruct rdopkg
to fetch review chain in local_patches_branch before continuing.

The patches remote must be a Gerrit endpoint.

### CODE REVIEW

**Comment by yac** [comment]
Thanks for the code, it gives me enough information on how to implement new gerrit patches workflow. However, I'd like to support both normal and gerrit patches seamleassly without passing an argument to each command.

Any idea how to detect normal/gerrit patches branches? If not, how about a simple convention? 

Alternatively, `rdoinfo` could store this information, but that seems unnecessary.

**Comment by cschwede** [comment]
Supporting normal and gerrit patches without passing another argument might be added on top of this - but as you said, it probably will require more changes to make this possible.
The idea behind this is to start with adding a review chain on Gerrit. We might need some follow ups to make this the new default (after the transition to Gerrit).

**Comment by apevec** [comment]
@cschwede @yac Yes, let's make this step by step while keep the old workflow working.
There will be some redundancies and imperfections but that can be refactored later.

**Comment by yac** [comment]
I need to refactor anyway on `pwnpkg` split so let's see how this code evolves in the wilderness :)

**Comment by apevec** [comment]
@yac pwnpkg refactoring is lower prio, let's first get rdopkg work with softwarefactory

**Pull request merged**
